services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
